name: CI
 
on:
  push:
    branches:
      - main
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
 
    - name: Build Java application
      run: javac Main.java
 
    - name: Build Docker image
      run: docker build -t your_username/my-java-app .
 
    - name: Push Docker image
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker push your_username/my-java-app
