name: Java CI
 
on:
  push:
    branches:
      - main
 
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Compile Java code
      run: javac src/Main.java
      
    - name: Build Docker image
      run: |
        docker build -t my-java-app .

    - name: Log in to Docker Hub
      run: docker login -u keerthikolati -p dckr_pat_WNAC2pxJKswhxkJ-Pm1sDgPH4U0
      
    - name: Push Docker image to Docker Hub
      run: docker push keerthikolati/my-java-app:latest
 
    - name: Run Docker container
      run: docker run my-java-app
