name: Java CI
 
on:
  push:
    branches:
      - main
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
 
    - name: Compile Java code
      run: javac Main.java
 
    - name: Build Docker image
      run: docker build -t my-java-app .
 
    - name: Run Docker container
      run: docker run my-java-app
