name: Java CI with Docker
 
on:
  push:
    branches:
      - main
 
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
 
    - name: Compile Java code
      run: javac Main.java
 
    - name: Navigate Dockerfile directory
      run: cd docker-file
 
    - name: Build Docker image
      run: |
        docker build -t keerthikolati/java-app:latest .
        docker tag keerthikolati/java-app:latest keerthikolati/java-app:${{ github.sha }}
 
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: keerthikolati
        password: ${{ secrets.DOCKER_PASSWORD }}
 
    - name: Push Docker image
      run: |
        docker push keerthikolati/java-app:latest
        docker push keerthikolati/java-app:${{ github.sha }}
