name: Java CI with Docker
 
on:
  push:
    branches:
      - main
 
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
 
    - name: Compile Java code
      run: javac Main.java

    - name: Clone repository
      run: git clone https://github.com/Keerthikolatis/javaapp.git
 
    - name: Build Docker image
      run: docker build -t java-app:latest javaapp

      
   
 
